services:
  - type: web
    name: telegram-gpt-bot
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_TOKEN
        value: YOUR_TELEGRAM_BOT_TOKEN
      - key: OPENAI_API_KEY
        value: YOUR_OPENAI_API_KEY
